# Dependencies

# Permalinks
permalink:        pretty

# Setup
title:            Jordan Hansen
tagline:          'Sports and culture and maybe some other stuff'
description:      An enterprising young reporter who wants to work for your media company because he needs a job.
url:              http://jordyhansen.github.io
baseurl:          /profile-hyde/
shortbaseurl:     /profile-hyde
colorscheme:      ''
#options '' (black), theme-base-08 (red), theme-base-09 (orange), theme-base-0a (yellow), theme-base-0b (green), theme-base-0c (cyan), theme-base-0d (blue), theme-base-0e (magenta), theme-base-0f (brown)


author:
  name:           'Jordan Hansen'
  url:            ''
  
paginate:         5

# Custom vars
version:          0.8.1

