# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Stella R. Student
tagline:          'Your tagline'
description:      A student journalist at the University of Iowa with a bright future ahead of her in mass communication.
url:              http://lathropd.github.io
baseurl:          /hyde/
shortbaseurl:     /hyde
theme:            'body'

author:
  name:           'Daniel Lathrop'
  url:            https://twitter.com/lathropd

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/lathropd/hyde
