# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Stella R. Student
tagline:          'Your tagline'
description:      University of Iowa student journalist.
url:              http://lathropd.github.io
baseurl:          /hyde/

author:
  name:           'Daniel Lathrop'
  url:            https://twitter.com/lathropd

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/lathropd/hyde
